name: Update variants
on:
  push:
    paths:
      - 'variants/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create local changes
        run: |
          cd variants
          ls *.sh > _list
          mkdir -p keywords
          rm -rf keywords/*
          ls *.sh | cut -d'.' -f1 | tr '-' '\n' | sort -u > keywords/_list
          cat keywords/_list | (while read w; do ls *.sh | grep -sw $w >> keywords/$w; done;)

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            branch: ${{ github.ref }}
