name: list-variants
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          cd variants
          ls *.sh | cut -d'.' -f1 | tr '-' '\n' | sort -u
